# Site settings
title: Charu Jain
description: 'Security and coding enthusiast'
url: 'https://charujain.org'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Charu Jain'
  email: charujain0003@gmail.com
  twitter_username: CharuJa41228001
  facebook_username: charujainaskn
  github_username:  cjc0d3
  linkedin_username:  charu-jain-596973141

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
